version: "2"  # optional since v1.27.0
services:
  jupyter:
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - "9000:8888"
      - "9001:8501"
    volumes:
      - ./notebooks:/home/jovyan/notebooks:rw
      - ./streamlit:/home/jovyan/streamlit:rw
    environment:
      - GRANT_SUDO=yes
